### ISSUE TITLE
Error when parsing Rails generated ActiveStorage migration

### ISSUE THREAD

**Issue by veganstraightedge** [robotdana/leftovers#14]
This appeared after we upgraded from 0.8 to 0.9.

```
> leftovers

/Users/s/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/leftovers-0.9.0/lib/leftovers/matchers/node_type.rb:17:in `===': undefined method `type' for #<Leftovers::DefinitionNode:0x000000011b851f58 @node=s(:sym, :blob), @name=:blob, @loc=#<Parser::Source::Range db/migrate/20220125225312_create_active_storage_tables.active_storage.rb 1537...1542>> (NoMethodError)
from /Users/s/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/leftovers-0.9.0/lib/leftovers/matchers/and.rb:18:in `==='
from /Users/s/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/leftovers-0.9.0/lib/leftovers/matchers/any.rb:18:in `block in ==='
from /Users/s/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/leftovers-0.9.0/lib/leftovers/matchers/any.rb:17:in `any?'
from /Users/s/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/leftovers-0.9.0/lib/leftovers/matchers/any.rb:17:in `==='
from /Users/s/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/leftovers-0.9.0/lib/leftovers/definition_to_add.rb:18:in `keep?'
from /Users/s/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/leftovers-0.9.0/lib/leftovers/definition_collection.rb:31:in `block (2 levels) in to_definitions'
from /Users/s/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/leftovers-0.9.0/lib/leftovers/definition_collection.rb:31:in `any?'
from /Users/s/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/leftovers-0.9.0/lib/leftovers/definition_collection.rb:31:in `block in to_definitions'
from /Users/s/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/leftovers-0.9.0/lib/leftovers/definition_collection.rb:30:in `map'
from /Users/s/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/leftovers-0.9.0/lib/leftovers/definition_collection.rb:30:in `to_definitions'
from /Users/s/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/leftovers-0.9.0/lib/leftovers/file_collector.rb:80:in `definitions'
from /Users/s/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/leftovers-0.9.0/lib/leftovers/file_collector.rb:29:in `to_h'
from /Users/s/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/leftovers-0.9.0/lib/leftovers/collector.rb:43:in `collect_file'
from /Users/s/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/leftovers-0.9.0/lib/leftovers/collector.rb:32:in `block in collect_file_list'
from /Users/s/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/parallel-1.21.0/lib/parallel.rb:515:in `call_with_index'
from /Users/s/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/parallel-1.21.0/lib/parallel.rb:485:in `process_incoming_jobs'
from /Users/s/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/parallel-1.21.0/lib/parallel.rb:465:in `block in worker'
from /Users/s/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/parallel-1.21.0/lib/parallel.rb:456:in `fork'
from /Users/s/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/parallel-1.21.0/lib/parallel.rb:456:in `worker'
from /Users/s/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/parallel-1.21.0/lib/parallel.rb:447:in `block in create_workers'
from /Users/s/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/parallel-1.21.0/lib/parallel.rb:446:in `each'
from /Users/s/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/parallel-1.21.0/lib/parallel.rb:446:in `each_with_index'
from /Users/s/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/parallel-1.21.0/lib/parallel.rb:446:in `create_workers'
from /Users/s/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/parallel-1.21.0/lib/parallel.rb:386:in `work_in_processes'
from /Users/s/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/parallel-1.21.0/lib/parallel.rb:289:in `map'
from /Users/s/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/parallel-1.21.0/lib/parallel.rb:238:in `each'
from /Users/s/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/leftovers-0.9.0/lib/leftovers/collector.rb:31:in `collect_file_list'
from /Users/s/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/leftovers-0.9.0/lib/leftovers/collector.rb:22:in `collect'
from /Users/s/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/leftovers-0.9.0/lib/leftovers.rb:95:in `leftovers'
from /Users/s/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/leftovers-0.9.0/lib/leftovers.rb:103:in `run'
from /Users/s/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/leftovers-0.9.0/lib/leftovers/cli.rb:17:in `block in run'
from /Users/s/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/leftovers-0.9.0/lib/leftovers/cli.rb:13:in `catch'
from /Users/s/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/leftovers-0.9.0/lib/leftovers/cli.rb:13:in `run'
from /Users/s/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/leftovers-0.9.0/exe/leftovers:6:in `<top (required)>'
from /Users/s/.rbenv/versions/3.0.3/bin/leftovers:25:in `load'
from /Users/s/.rbenv/versions/3.0.3/bin/leftovers:25:in `<main>'
```

**Comment by robotdana** [comment]
hi, sorry i missed this for a couple months, i'm configuring notification for this project now i didn't realise i didn't have it set.

i'll look at this tonight

**Comment by robotdana** [comment]
@veganstraightedge @marteuscruz-morningstar This should be fixed in 0.10.0, and also now that i've turned notifications on for this repo i should get to these things sooner than 2 months later :)

**Comment by veganstraightedge** [comment]
Thank you! I'll give `0.10.0` a try.

**Comment by veganstraightedge** [comment]
Btw, 0.10.0 is working for us again. Thanks!

**Comment by mateuscruz-morningstar** [comment]
Thank you! It's working again.
