### ISSUE TITLE
Could you please kindly support on Ruby 3.2

### ISSUE THREAD

**Issue by JuanLUJoanne** [robotdana/leftovers#23]
We had a failed build with leftover gem on ruby 3.2 

here is the traceback: 

bundler: failed to load command: leftovers (/usr/local/bundle/ruby/3.2.0/bin/leftovers)
--
  | /usr/local/bundle/ruby/3.2.0/gems/leftovers-0.11.2/lib/leftovers/file_collector/node_processor.rb:103:in `on_block_pass': undefined method `sym?' for nil:NilClass (NoMethodError)
  | from /usr/local/bundle/ruby/3.2.0/gems/ast-2.4.2/lib/ast/processor/mixin.rb:259:in `process'
  | from /usr/local/bundle/ruby/3.2.0/gems/ast-2.4.2/lib/ast/processor/mixin.rb:276:in `block in process_all'
  | from /usr/local/bundle/ruby/3.2.0/gems/ast-2.4.2/lib/ast/processor/mixin.rb:275:in `map'
  | from /usr/local/bundle/ruby/3.2.0/gems/ast-2.4.2/lib/ast/processor/mixin.rb:275:in `process_all'
  | from /usr/local/bundle/ruby/3.2.0/gems/parser-3.2.0.0/lib/parser/ast/processor.rb:184:in `on_send'
  | from /usr/local/bundle/ruby/3.2.0/gems/leftovers-0.11.2/lib/leftovers/file_collector/node_processor.rb:69:in `on_send'
  | from /usr/local/bundle/ruby/3.2.0/gems/ast-2.4.2/lib/ast/processor/mixin.rb:259:in `process'
  | from /usr/local/bundle/ruby/3.2.0/gems/parser-3.2.0.0/lib/parser/ast/processor.rb:48:in `on_vasgn'
  | from /usr/local/bundle/ruby/3.2.0/gems/parser-3.2.0.0/lib/parser/ast/processor.rb:57:in `process_var_asgn_node'
  | from /usr/local/bundle/ruby/3.2.0/gems/ast-2.4.2/lib/ast/processor/mixin.rb:259:in `process'
  | from /usr/local/bundle/ruby/3.2.0/gems/ast-2.4.2/lib/ast/processor/mixin.rb:276:in `block in process_all'
  | from /usr/local/bundle/ruby/3.2.0/gems/ast-2.4.2/lib/ast/processor/mixin.rb:275:in `map'
  | from /usr/local/bundle/ruby/3.2.0/gems/ast-2.4.2/lib/ast/processor/mixin.rb:275:in `process_all'
  | from /usr/local/bundle/ruby/3.2.0/gems/parser-3.2.0.0/lib/parser/ast/processor.rb:11:in `process_regular_node'
  | from /usr/local/bundle/ruby/3.2.0/gems/ast-2.4.2/lib/ast/processor/mixin.rb:259:in `process'
  | from /usr/local/bundle/ruby/3.2.0/gems/parser-3.2.0.0/lib/parser/ast/processor.rb:163:in `on_def'
  | from /usr/local/bundle/ruby/3.2.0/gems/leftovers-0.11.2/lib/leftovers/file_collector/node_processor.rb:15:in `on_def'
  | from /usr/local/bundle/ruby/3.2.0/gems/ast-2.4.2/lib/ast/processor/mixin.rb:259:in `process'
  | from /usr/local/bundle/ruby/3.2.0/gems/ast-2.4.2/lib/ast/processor/mixin.rb:276:in `block in process_all'
  | from /usr/local/bundle/ruby/3.2.0/gems/ast-2.4.2/lib/ast/processor/mixin.rb:275:in `map'
  | from /usr/local/bundle/ruby/3.2.0/gems/ast-2.4.2/lib/ast/processor/mixin.rb:275:in `process_all'
  | from /usr/local/bundle/ruby/3.2.0/gems/parser-3.2.0.0/lib/parser/ast/processor.rb:11:in `process_regular_node'
  | from /usr/local/bundle/ruby/3.2.0/gems/ast-2.4.2/lib/ast/processor/mixin.rb:259:in `process'
  | from /usr/local/bundle/ruby/3.2.0/gems/ast-2.4.2/lib/ast/processor/mixin.rb:276:in `block in process_all'
  | from /usr/local/bundle/ruby/3.2.0/gems/ast-2.4.2/lib/ast/processor/mixin.rb:275:in `map'
  | from /usr/local/bundle/ruby/3.2.0/gems/ast-2.4.2/lib/ast/processor/mixin.rb:275:in `process_all'
  | from /usr/local/bundle/ruby/3.2.0/gems/leftovers-0.11.2/lib/leftovers/file_collector/node_processor.rb:111:in `on_class'
  | from /usr/local/bundle/ruby/3.2.0/gems/ast-2.4.2/lib/ast/processor/mixin.rb:259:in `process'
  | from /usr/local/bundle/ruby/3.2.0/gems/leftovers-0.11.2/lib/leftovers/file_collector.rb:41:in `collect'
  | from /usr/local/bundle/ruby/3.2.0/gems/leftovers-0.11.2/lib/leftovers/collector.rb:39:in `collect_file'
  | from /usr/local/bundle/ruby/3.2.0/gems/leftovers-0.11.2/lib/leftovers/collector.rb:30:in `block in collect_file_list'
  | from /usr/local/bundle/ruby/3.2.0/gems/parallel-1.22.1/lib/parallel.rb:587:in `call_with_index'
  | from /usr/local/bundle/ruby/3.2.0/gems/parallel-1.22.1/lib/parallel.rb:557:in `process_incoming_jobs'
  | from /usr/local/bundle/ruby/3.2.0/gems/parallel-1.22.1/lib/parallel.rb:537:in `block in worker'
  | from /usr/local/bundle/ruby/3.2.0/gems/parallel-1.22.1/lib/parallel.rb:528:in `fork'
  | from /usr/local/bundle/ruby/3.2.0/gems/parallel-1.22.1/lib/parallel.rb:528:in `worker'
  | from /usr/local/bundle/ruby/3.2.0/gems/parallel-1.22.1/lib/parallel.rb:519:in `block in create_workers'
  | from /usr/local/bundle/ruby/3.2.0/gems/parallel-1.22.1/lib/parallel.rb:518:in `each'
  | from /usr/local/bundle/ruby/3.2.0/gems/parallel-1.22.1/lib/parallel.rb:518:in `each_with_index'
  | from /usr/local/bundle/ruby/3.2.0/gems/parallel-1.22.1/lib/parallel.rb:518:in `create_workers'
  | from /usr/local/bundle/ruby/3.2.0/gems/parallel-1.22.1/lib/parallel.rb:457:in `work_in_processes'
  | from /usr/local/bundle/ruby/3.2.0/gems/parallel-1.22.1/lib/parallel.rb:294:in `map'
  | from /usr/local/bundle/ruby/3.2.0/gems/parallel-1.22.1/lib/parallel.rb:238:in `each'
  | from /usr/local/bundle/ruby/3.2.0/gems/leftovers-0.11.2/lib/leftovers/collector.rb:29:in `collect_file_list'
  | from /usr/local/bundle/ruby/3.2.0/gems/leftovers-0.11.2/lib/leftovers/collector.rb:23:in `collect'
  | from /usr/local/bundle/ruby/3.2.0/gems/leftovers-0.11.2/lib/leftovers/runner.rb:24:in `collection'
  | from /usr/local/bundle/ruby/3.2.0/gems/leftovers-0.11.2/lib/leftovers/runner.rb:9:in `run'
  | from /usr/local/bundle/ruby/3.2.0/gems/leftovers-0.11.2/lib/leftovers/cli.rb:15:in `block in run'
  | from /usr/local/bundle/ruby/3.2.0/gems/leftovers-0.11.2/lib/leftovers/cli.rb:12:in `catch'
  | from /usr/local/bundle/ruby/3.2.0/gems/leftovers-0.11.2/lib/leftovers/cli.rb:12:in `run'
  | from /usr/local/bundle/ruby/3.2.0/gems/leftovers-0.11.2/exe/leftovers:8:in `<top (required)>'
  | from /usr/local/bundle/ruby/3.2.0/bin/leftovers:25:in `load'
  | from /usr/local/bundle/ruby/3.2.0/bin/leftovers:25:in `<top (required)>'
  | from /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/cli/exec.rb:58:in `load'
  | from /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/cli/exec.rb:58:in `kernel_load'
  | from /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/cli/exec.rb:23:in `run'
  | from /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/cli.rb:486:in `exec'
  | from /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  | from /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  | from /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  | from /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/cli.rb:31:in `dispatch'
  | from /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  | from /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/cli.rb:25:in `start'
  | from /usr/local/bundle/gems/bundler-2.3.26/exe/bundle:48:in `block in <top (required)>'
  | from /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
  | from /usr/local/bundle/gems/bundler-2.3.26/exe/bundle:36:in `<top (required)>'
  | from /usr/local/bin/bundle:25:in `load'
  | from /usr/local/bin/bundle:25:in `<main>'
  | ERROR: 1
  | ⚠️ Failed to run command, exited with 1, run params: | 0s
  | -f docker-compose.buildkite-18724-override.yml run --name buildkite018614b0718a4c99863bb5f4e62afbf5_market-storefront-test_build_18724 --no-deps --rm market-storefront-test /bin/sh -e -c bundle exec leftovers
  | 🚨 Error: The command exited with status 1
  | user command error: The plugin docker-compose command hook exited with status 1

**Comment by robotdana** [comment]
please include a snippet from the file this fails on

**Comment by robotdana** [comment]
This should be fixed by 0.12.1. please feel free to reopen if it's not.
